In [33]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/covid-data/covid_synthetic_dataset.csv

In [36]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
df=pd.read_csv('/kaggle/input/covid-data/covid_synthetic_dataset.csv')
df

   age  gender  fever cough       city has_covid
0   60    Male  103.0  Mild    Kolkata        No
1   42    Male  100.0  Mild      Delhi       Yes
2   31  Female  101.0  Mild      Delhi        No
3   65    Male  101.0  Mild     Mumbai        No
4   81  Female  101.0  Mild     Mumbai        No
5   80    Male  100.0  Mild  Bangalore        No

In [37]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   42    Male  100.0  Mild    Delhi       Yes
2   31  Female  101.0  Mild    Delhi        No
3   65    Male  101.0  Mild   Mumbai        No
4   81  Female  101.0  Mild   Mumbai        No

In [38]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [39]:
import pandas as pd
from sklearn.model_selection import train_test_split
df = pd.read_csv('/kaggle/input/covid-data/covid_synthetic_dataset.csv')
X = df.drop('has_covid', axis=1)
y = df['has_covid']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
X_train.head()

   age  gender  fever cough       city
5   80    Male  100.0  Mild  Bangalore
1   42    Male  100.0  Mild      Delhi
4   81  Female  101.0  Mild     Mumbai
2   31  Female  101.0  Mild      Delhi

In [40]:
from sklearn.impute import SimpleImputer
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])
X_test_fever = si.fit_transform(X_test[['fever']])
X_train_fever.shape

(4, 1)

In [44]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[['Mild', 'Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])
X_test_cough = oe.transform(X_test[['cough']])
X_train_cough.shape

(4, 1)

In [48]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(drop='first', sparse=False, handle_unknown='ignore')  # ✅ Add handle_unknown
X_train_gender_city = ohe.fit_transform(X_train[['gender', 'city']])
X_test_gender_city = ohe.transform(X_test[['gender', 'city']])

In [47]:
X_train_age=X_train.drop(columns=['gender','fever','cough','city']).values
X_test_age=X_train.drop(columns=['gender','fever','cough','city']).values
X_train_age.shape

(4, 1)

In [13]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

transformer = ColumnTransformer(
    transformers=[
        ('tnf1', SimpleImputer(), ['fever']),
        ('tnf2', OrdinalEncoder(categories=[['Mild', 'Strong']]), ['cough']),
        ('tnf3', OneHotEncoder(sparse=False, drop='first'), ['gender', 'city'])
    ],
    remainder='passthrough'
)
transformed_data = transformer.fit_transform(X_train)
print(transformed_data.shape)

(4, 7)

In [14]:
transformer.transform(X_test).shape

(2, 7)

In [15]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer

transformer1 = ColumnTransformer(
    transformers=[
        ('imputer', SimpleImputer(), ['fever'])
    ],
    remainder='passthrough'
)

transformer1.fit(X_train)

transformed_X_test = transformer1.transform(X_test)

print(transformed_X_test.shape)

(2, 5)

In [17]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv("/kaggle/input/covid-data/covid_synthetic_dataset.csv", encoding='latin1')
data.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   42    Male  100.0  Mild    Delhi       Yes
2   31  Female  101.0  Mild    Delhi        No
3   65    Male  101.0  Mild   Mumbai        No
4   81  Female  101.0  Mild   Mumbai        No